# zmodload zsh/zprof

# brew info zplug
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
zplug "plugins/brew", from:oh-my-zsh
zplug "plugins/common-aliases", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh

zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug "desyncr/auto-ls"
zplug "djui/alias-tips" 

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
	printf "Install? [y/N]: "
	if read -q; then
		echo; zplug install
	fi
fi

# Then, source plugins and add commands to $PATH
zplug load

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

setopt no_beep

# Do not write a duplicate event to the history file.
setopt HIST_SAVE_NO_DUPS         

path=(
  $HOME/bin
  /usr/local/bin
  /usr/local/sbin
  $path
)

# brew info coreutils
[[ -f /usr/local/opt/coreutils/libexec/gnubin ]] && path=("/usr/local/opt/coreutils/libexec/gnubin" $path)

if type go &>/dev/null; then
  path=($(go env GOPATH)/bin $path)
fi

typeset -U path

# brew info chruby
if type chruby-exec &>/dev/null; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
fi


# brew install direnv, https://github.com/zimbatm/direnv#zsh
if type direnv &>/dev/null; then
  eval "$(direnv hook zsh)"
fi

# brew install starship
if type starship &>/dev/null; then
  eval "$(starship init zsh)"
fi

# brew info z
[[ -f /usr/local/etc/profile.d/z.sh ]] && source /usr/local/etc/profile.d/z.sh

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# load custom executable functions
for function in $ZDOTDIR/functions/*; do
  source $function
done

# generated by `/usr/local/opt/fzf/install`
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zprof
