tap caskroom/cask
install ack
install asciidoc
install boost
install boost-build
install brew-cask
install casperjs
install chrome-cli
install couchdb
install ctags
install direnv
install dos2unix
install easy-tag
install git
install gradle
install groovy
install gsl
install gtkmm
install jenkins
install jq
install libyaml
# require Xcode
install macvim --override-system-vim
install mongodb
install mysql
install neon
install nginx
install nmap
install nvm
install popt
install pstree
install python
install rbenv-gem-rehash
install reattach-to-user-namespace
install redis
install ruby-build
install scala
install siege
install sonar
install sonar-runner
install subversion
install the_silver_searcher
install tig
install tmux
install trash
install tree
install w3m
install watch
install wxmac
install xmlto
install z
install zsh-syntax-highlighting
