install ack
install asciidoc
install autojump
install boost-build
install brew-cask
install casperjs
install couchdb
install ctags
install dart
install direnv
install dos2unix
install easy-tag
install editorconfig
install fish
install fontforge
install gdal
install gibo
install git
install gnu-sed
install gradle
install gsl
install gtkmm
install hub
install jq
install lame
install libyaml
install lua
install mackup
install macvim --override-system-vim --with-luajit
install meld
install mongodb
install neon
install nginx
install nmap
install node
install nvm
install popt
install pstree
install python
install rbenv-gem-rehash
install rbenv-gemset
install reattach-to-user-namespace
install redis
install rethinkdb
install ruby-build
install siege
install sonar
install sonar-runner
install subversion
install the_platinum_searcher
install the_silver_searcher
install tig
install tmux
install trash
install tree
install ttfautohint
install v
install w3m
install watch
install xmlto
install youtube-dl
install z
install zsh-syntax-highlighting
