set nocompatible
" otherwise NERDTree shows strange character instead of arrows
set encoding=utf-8

if empty(glob('~/.vim/autoload/plug.vim'))
  !mkdir -p ~/.vim/autoload
  !curl -fLo ~/.vim/autoload/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" vim-plug, install under ~/.vim/plugged
call plug#begin('~/.vim/plugged')

Plug 'Lokaltog/vim-easymotion'
Plug 'Raimondi/delimitMate'
Plug 'Valloric/MatchTagAlways'
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }
Plug 'Yggdroot/indentLine'
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/vim-emoji'
Plug 'kien/ctrlp.vim'
Plug 'myusuf3/numbers.vim'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'terryma/vim-multiple-cursors'
Plug 'tommcdo/vim-exchange'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-characterize'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
" Git
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
" snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
" Front-End
Plug 'ap/vim-css-color'
Plug 'digitaltoad/vim-jade'
Plug 'maksimr/vim-jsbeautify'
Plug 'mattn/emmet-vim'
Plug 'othree/html5.vim'
" Javascript & Node.js
Plug 'jelera/vim-javascript-syntax'
Plug 'kchmck/vim-coffee-script'
Plug 'marijnh/tern_for_vim', { 'do': 'npm i' }
Plug 'moll/vim-node'
" colorscheme
Plug 'chriskempson/tomorrow-theme', { 'rtp': 'vim' }
Plug 'daylerees/colour-schemes', { 'rtp': 'vim' }
Plug 'flazz/vim-colorschemes'

call plug#end()

" syntastic: error: your shell /usr/local/bin/fish doesn't use traditional UNIX syntax for redirections
set shell=/bin/sh

silent! colorscheme Tomorrow-Night

let mapleader=','

imap jk <Esc>

" ~/.vimrc
" *** The Right Hand system ***
" in INSERT mode, escape to NORMAL mode
inoremap ;l <Esc>
" in INSERT mode, save & back to NORMAL mode
inoremap ;k <Esc>:update<CR>
" in INSERT mode, save & back to INSERT mode
inoremap ;j <C-O>:update<CR>
" in NORMAL mode, save & back to NORMAL mode
nnoremap ;j :update<CR>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Allow hidden buffers, don't limit to 1 file per window/split
set hidden

set number

" turn off backup for now
set nobackup
set noswapfile

" change the terminal's title
set title

set hlsearch
set ignorecase
set smartcase

" use soft tab
set expandtab
set tabstop=2
" number of space to use for autoindenting
set shiftwidth=2

" toggle paste mode
set pastetoggle=<F2>

" enable mouse in all modes
set mouse=a

" cut down key stroke for normal mode
" but lose the capability for repeating the linewise character searches
"nnoremap ; :

" Disable all arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Easy pane navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" git commit message
autocmd Filetype gitcommit setlocal spell textwidth=72

" turn on spell checking for markdown files
autocmd BufRead,BufNewFile *.md setlocal spell

" turn off search highlight
nnoremap <silent> <leader><space> :noh<CR>

" The Silver Searcher, http://robots.thoughtbot.com/faster-grepping-in-vim/
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  "let g:ctrlp_user_command = 'ag %s -U -l --nocolor -g ""'
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  "let g:ctrlp_use_caching = 0
endif

" ctrlp
let g:ctrlp_cmd = 'CtrlPBuffer'
let g:ctrlp_working_path_mode = 'ra'

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" emmet-vim, enable just for html/css
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall

" NERDTree
autocmd vimenter * if !argc() | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" NERDTree mirror mode by default
map <silent> <leader>n :NERDTreeToggle<CR> :NERDTreeMirror<CR>

let NERDTreeIgnore=['\.sublime-*']

" numbers.vim
nnoremap <F3> :NumbersToggle<CR>
nnoremap <F4> :NumbersOnOff<CR>

" vim-easy-align
" Start interactive EasyAlign in visual mode
vmap <Enter> <Plug>(EasyAlign)
" Start interactive EasyAlign with a Vim movement
nmap <Leader>a <Plug>(EasyAlign)

" vim-jsbeautify
autocmd FileType javascript noremap <buffer>  <c-f> :call JsBeautify()<cr>
autocmd FileType html noremap <buffer> <c-f> :call HtmlBeautify()<cr>
autocmd FileType css noremap <buffer> <c-f> :call CSSBeautify()<cr>
autocmd FileType javascript vnoremap <buffer>  <c-f> :call RangeJsBeautify()<cr>
autocmd FileType html vnoremap <buffer> <c-f> :call RangeHtmlBeautify()<cr>
autocmd FileType css vnoremap <buffer> <c-f> :call RangeCSSBeautify()<cr>

" tern_for_vim
let g:tern_show_argument_hints='on_hold'
nmap <Leader>tD :TernDoc<cr>
nmap <Leader>tb :TernDocBrowse<cr>
nmap <Leader>td :TernDef<cr>
nmap <Leader>tr :TernRefs<cr>
nmap <Leader>tR :TernRename<cr>

" enable code folding by "vim-javascript-syntax'
"au FileType javascript call JavaScriptFold()

" to avoid conflict with YouCompleteMe
set rtp+=~/dotfiles/vim/
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsSnippetsDir="~/dotfiles/vim/snips/"
let g:UltiSnipsSnippetDirectories=["UltiSnips", "snips"]

" syntastic
let g:syntastic_javascript_checkers = ['jsxhint']

" vim-emoji
"   - enable only when editing Markdown files
"   - trigger by CTRL-X CTRL-U in INSERT mode with terminal vim
augroup emoji_complete
  autocmd!
  autocmd FileType markdown setlocal completefunc=emoji#complete
augroup END

" Using Emojis as Git Gutter symbols, work only with terminal vim(?)
silent! if emoji#available()
  let g:gitgutter_sign_added = emoji#for('small_blue_diamond')
  let g:gitgutter_sign_modified = emoji#for('small_orange_diamond')
  let g:gitgutter_sign_removed = emoji#for('small_red_triangle')
  let g:gitgutter_sign_modified_removed = emoji#for('collision')
endif

" SHIFT + direction to change tab
noremap <S-l> gt
noremap <S-h> gT

nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>sv :so $MYVIMRC<CR>

" copy from easy-motion
"let g:EasyMotion_do_mapping = 0 " Disable default mappings

" Bi-directional find motion
" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `s{char}{label}`
nmap s <Plug>(easymotion-s)
" or
" `s{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
nmap s <Plug>(easymotion-s2)

" Turn on case sensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
