set nocompatible
syntax on
filetype off
set rtp+=~/dotfiles/vim/bundle/vundle/
call vundle#rc()

" Vundle
Bundle 'gmarik/vundle'
Bundle 'tpope/vim-sensible'
Bundle 'kien/ctrlp.vim'
Bundle 'bling/vim-airline'
Bundle 'othree/html5.vim'

" colorscheme
Bundle 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}

colorscheme Tomorrow-Night

filetype plugin indent on

" Change leader
let mapleader=","
" let g:mapleader=","

set number
" turn off backup for now
set hlsearch
set smartcase

" Disable all arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" git commit message
autocmd Filetype gitcommit spell textwidth=72
" turn on spell checking for markdown files
autocmd BufRead,BufNewFile *.md setlocal spell

" The Silver Searcher, http://robots.thoughtbot.com/faster-grepping-in-vim/
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  "let g:ctrlp_use_caching = 0
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
