matches:
  - trigger: ";dl"
    replace: "docker logs --follow "
  - trigger: ";lh"
    replace: "localhost:"
  - trigger: ";occ"
    replace: "openssl s_client -connect "
  - trigger: ";py"
    replace: "python"
  - trigger: ";su"
    replace: "sudo -i"
