matches:
  - trigger: ";dl"
    replace: "docker logs --follow "
  - trigger: ";lh"
    replace: "localhost:"
  - trigger: ";occ"
    replace: "openssl s_client -connect "
  - trigger: ";py"
    replace: "python"
  - trigger: ";su"
    replace: "sudo -i"

  # Home(b)rew
  - trigger: ";bi"
    replace: "brew install "
  - trigger: ";bs"
    replace: "brew search "
  - trigger: ";bbc"
    replace: "brew bundle cleanup"
  - trigger: ";bbd"
    replace: "brew bundle dump --force"
  - trigger: ";bbi"
    replace: "brew bundle install -v --no-lock"
