export LC_ALL=$LANG

export EDITOR=`which vim`

# set 'ag' as the default source for 'fzf'
export FZF_DEFAULT_COMMAND='ag --skip-vcs-ignores -g ""'

# `brew info coreutils`
export MANPATH="/usr/local/coreutils/libexec/gnuman:$MANPATH"

