# To make all entries of `locale` use "en_US.UTF-8"
export LANG=en_US.UTF-8
export LC_ALL=$LANG

export EDITOR=`which vim`

# set 'ag' as the default source for 'fzf'
export FZF_DEFAULT_COMMAND='ag --skip-vcs-ignores -g ""'

# `brew info coreutils`
export MANPATH="/usr/local/coreutils/libexec/gnuman:$MANPATH"

